import type { RecipeTemplate } from '../types'

// Base de recettes candidates pour le moteur d'optimisation.
// freshnessTier : 1 = protéine ultra-fraîche (poisson, volaille crue, œufs) à cuisiner tôt dans la semaine
//                 2 = conservation moyenne (fromage frais, viande cuite, légumes frais robustes)
//                 3 = longue conservation (légumineuses, féculents secs, surgelés, conserves)
export const RECIPE_POOL: RecipeTemplate[] = [
  // --- Petit-déjeuner ---
  {
    id: 'r-pdj-1',
    slot: 'petit-dejeuner',
    name: 'Skyr, flocons d’avoine & fruits rouges',
    kcal: 380,
    protein: 28,
    carbs: 45,
    fat: 9,
    prepTime: 5,
    cost: 1.6,
    freshnessTier: 2,
    allergenTags: ['Lactose', 'Gluten'],
    highGI: false,
    image: '🥣',
    ingredients: [
      { name: 'Skyr nature', quantity: '200 g' },
      { name: 'Flocons d’avoine', quantity: '50 g' },
      { name: 'Fruits rouges surgelés', quantity: '80 g' },
      { name: 'Miel', quantity: '1 c. à c.' },
    ],
    steps: ['Mélanger le skyr et les flocons d’avoine.', 'Ajouter les fruits rouges décongelés 1 min au micro-ondes.', 'Terminer avec un filet de miel.'],
  },
  {
    id: 'r-pdj-2',
    slot: 'petit-dejeuner',
    name: 'Œufs brouillés, avocat & pain complet',
    kcal: 410,
    protein: 24,
    carbs: 32,
    fat: 20,
    prepTime: 8,
    cost: 2.1,
    freshnessTier: 1,
    allergenTags: ['Œufs', 'Gluten'],
    highGI: false,
    image: '🍳',
    ingredients: [
      { name: 'Œufs', quantity: '3' },
      { name: 'Avocat', quantity: '1/2' },
      { name: 'Pain complet', quantity: '2 tranches' },
    ],
    steps: ['Brouiller les œufs à feu doux.', 'Griller le pain, écraser l’avocat dessus.', 'Servir ensemble.'],
  },
  {
    id: 'r-pdj-3',
    slot: 'petit-dejeuner',
    name: 'Porridge banane & beurre de cacahuète',
    kcal: 420,
    protein: 18,
    carbs: 55,
    fat: 14,
    prepTime: 6,
    cost: 1.3,
    freshnessTier: 3,
    allergenTags: ['Gluten', 'Arachides', 'Lactose'],
    highGI: true,
    image: '🥣',
    ingredients: [
      { name: 'Flocons d’avoine', quantity: '60 g' },
      { name: 'Lait demi-écrémé', quantity: '200 ml' },
      { name: 'Banane', quantity: '1' },
      { name: 'Beurre de cacahuète', quantity: '1 c. à c.' },
    ],
    steps: ['Chauffer flocons + lait 3 min.', 'Trancher la banane dessus.', 'Ajouter le beurre de cacahuète.'],
  },
  {
    id: 'r-pdj-4',
    slot: 'petit-dejeuner',
    name: 'Bowl cottage cheese, granola & kiwi',
    kcal: 360,
    protein: 30,
    carbs: 38,
    fat: 10,
    prepTime: 4,
    cost: 1.9,
    freshnessTier: 2,
    allergenTags: ['Lactose', 'Fruits à coque'],
    highGI: false,
    image: '🥣',
    ingredients: [
      { name: 'Cottage cheese', quantity: '200 g' },
      { name: 'Granola', quantity: '35 g' },
      { name: 'Kiwi', quantity: '2' },
    ],
    steps: ['Disposer le cottage cheese dans un bol.', 'Ajouter le granola et le kiwi coupé en dés.'],
  },
  {
    id: 'r-pdj-5',
    slot: 'petit-dejeuner',
    name: 'Pancakes protéinés à la banane',
    kcal: 440,
    protein: 32,
    carbs: 48,
    fat: 12,
    prepTime: 12,
    cost: 2.0,
    freshnessTier: 1,
    allergenTags: ['Œufs', 'Lactose'],
    highGI: true,
    image: '🥞',
    ingredients: [
      { name: 'Œufs', quantity: '2' },
      { name: 'Banane', quantity: '1' },
      { name: 'Whey protéine', quantity: '30 g' },
      { name: 'Flocons d’avoine', quantity: '30 g' },
    ],
    steps: ['Mixer tous les ingrédients.', 'Cuire les pancakes 2 min de chaque côté.'],
  },
  {
    id: 'r-pdj-6',
    slot: 'petit-dejeuner',
    name: 'Toast avocat, œuf poché & graines',
    kcal: 390,
    protein: 20,
    carbs: 30,
    fat: 22,
    prepTime: 10,
    cost: 2.3,
    freshnessTier: 1,
    allergenTags: ['Œufs', 'Gluten'],
    highGI: false,
    image: '🥑',
    ingredients: [
      { name: 'Pain complet', quantity: '2 tranches' },
      { name: 'Avocat', quantity: '1/2' },
      { name: 'Œuf', quantity: '1' },
      { name: 'Graines de sésame', quantity: '1 c. à c.' },
    ],
    steps: ['Pocher l’œuf 3 min.', 'Griller le pain et écraser l’avocat.', 'Déposer l’œuf et parsemer de graines.'],
  },
  {
    id: 'r-pdj-7',
    slot: 'petit-dejeuner',
    name: 'Smoothie bowl mangue & chia',
    kcal: 350,
    protein: 14,
    carbs: 58,
    fat: 8,
    prepTime: 6,
    cost: 2.4,
    freshnessTier: 2,
    allergenTags: ['Lactose'],
    highGI: true,
    image: '🥭',
    ingredients: [
      { name: 'Mangue surgelée', quantity: '150 g' },
      { name: 'Yaourt grec', quantity: '150 g' },
      { name: 'Graines de chia', quantity: '1 c. à s.' },
    ],
    steps: ['Mixer mangue et yaourt.', 'Verser dans un bol et parsemer de graines de chia.'],
  },
  {
    id: 'r-pdj-8',
    slot: 'petit-dejeuner',
    name: 'Tartines de pain complet, houmous & tomates',
    kcal: 340,
    protein: 14,
    carbs: 42,
    fat: 12,
    prepTime: 5,
    cost: 1.5,
    freshnessTier: 3,
    allergenTags: ['Gluten', 'Soja'],
    highGI: false,
    image: '🍅',
    ingredients: [
      { name: 'Pain complet', quantity: '2 tranches' },
      { name: 'Houmous', quantity: '60 g' },
      { name: 'Tomates cerises', quantity: '80 g' },
    ],
    steps: ['Tartiner le houmous sur le pain.', 'Ajouter les tomates cerises coupées en deux.'],
  },

  // --- Midi ---
  {
    id: 'r-midi-1',
    slot: 'midi',
    name: 'Bowl de poulet, quinoa & légumes rôtis',
    kcal: 620,
    protein: 42,
    carbs: 58,
    fat: 18,
    prepTime: 12,
    cost: 3.4,
    freshnessTier: 1,
    allergenTags: [],
    highGI: false,
    image: '🍗',
    ingredients: [
      { name: 'Blanc de poulet', quantity: '150 g' },
      { name: 'Quinoa cuit', quantity: '150 g' },
      { name: 'Courgette', quantity: '1' },
      { name: 'Poivron', quantity: '1/2' },
      { name: 'Huile d’olive', quantity: '1 c. à s.' },
    ],
    steps: ['Saisir le poulet coupé en dés 6 min à la poêle.', 'Faire revenir les légumes 5 min.', 'Dresser sur le quinoa chaud, assaisonner.'],
  },
  {
    id: 'r-midi-2',
    slot: 'midi',
    name: 'Wrap thon, crème citronée & crudités',
    kcal: 560,
    protein: 34,
    carbs: 50,
    fat: 22,
    prepTime: 10,
    cost: 2.9,
    freshnessTier: 2,
    allergenTags: ['Gluten', 'Poisson / Crustacés', 'Lactose'],
    highGI: false,
    image: '🌯',
    ingredients: [
      { name: 'Tortilla complète', quantity: '2' },
      { name: 'Thon au naturel', quantity: '160 g' },
      { name: 'Fromage frais léger', quantity: '40 g' },
      { name: 'Carotte râpée', quantity: '50 g' },
    ],
    steps: ['Mélanger thon et fromage frais + citron.', 'Garnir les tortillas de crudités.', 'Rouler et couper en deux.'],
  },
  {
    id: 'r-midi-3',
    slot: 'midi',
    name: 'Salade de pâtes, mozzarella & tomates',
    kcal: 600,
    protein: 26,
    carbs: 70,
    fat: 22,
    prepTime: 14,
    cost: 2.6,
    freshnessTier: 2,
    allergenTags: ['Gluten', 'Lactose'],
    highGI: true,
    image: '🍝',
    ingredients: [
      { name: 'Pâtes complètes', quantity: '90 g (poids sec)' },
      { name: 'Mozzarella light', quantity: '80 g' },
      { name: 'Tomates cerises', quantity: '150 g' },
      { name: 'Basilic', quantity: 'quelques feuilles' },
    ],
    steps: ['Cuire les pâtes al dente, refroidir.', 'Mélanger avec mozzarella et tomates.', 'Assaisonner huile d’olive et basilic.'],
  },
  {
    id: 'r-midi-4',
    slot: 'midi',
    name: 'Buddha bowl pois chiches & tahini',
    kcal: 580,
    protein: 22,
    carbs: 66,
    fat: 20,
    prepTime: 15,
    cost: 2.2,
    freshnessTier: 3,
    allergenTags: ['Soja'],
    highGI: false,
    image: '🥗',
    ingredients: [
      { name: 'Pois chiches cuits', quantity: '200 g' },
      { name: 'Riz complet', quantity: '80 g (poids sec)' },
      { name: 'Chou rouge', quantity: '80 g' },
      { name: 'Sauce tahini', quantity: '1 c. à s.' },
    ],
    steps: ['Rôtir les pois chiches 10 min au four.', 'Cuire le riz.', 'Dresser et napper de tahini.'],
  },
  {
    id: 'r-midi-5',
    slot: 'midi',
    name: 'Saumon vapeur, riz complet & brocolis',
    kcal: 610,
    protein: 38,
    carbs: 52,
    fat: 22,
    prepTime: 18,
    cost: 4.6,
    freshnessTier: 1,
    allergenTags: ['Poisson / Crustacés'],
    highGI: false,
    image: '🐟',
    ingredients: [
      { name: 'Pavé de saumon', quantity: '140 g' },
      { name: 'Riz complet', quantity: '80 g (poids sec)' },
      { name: 'Brocolis', quantity: '200 g' },
      { name: 'Citron', quantity: '1/2' },
    ],
    steps: ['Cuire le riz complet 20 min.', 'Cuire le saumon et les brocolis à la vapeur 10 min.', 'Arroser de jus de citron avant de servir.'],
  },
  {
    id: 'r-midi-6',
    slot: 'midi',
    name: 'Poke bowl dinde, edamame & mangue',
    kcal: 590,
    protein: 40,
    carbs: 60,
    fat: 15,
    prepTime: 13,
    cost: 3.8,
    freshnessTier: 1,
    allergenTags: ['Soja'],
    highGI: false,
    image: '🥙',
    ingredients: [
      { name: 'Escalope de dinde', quantity: '150 g' },
      { name: 'Riz vinaigré', quantity: '150 g' },
      { name: 'Edamame', quantity: '60 g' },
      { name: 'Mangue', quantity: '80 g' },
    ],
    steps: ['Cuire la dinde en lamelles.', 'Dresser sur le riz vinaigré.', 'Ajouter edamame et mangue.'],
  },
  {
    id: 'r-midi-7',
    slot: 'midi',
    name: 'Chili sin carne, riz basmati',
    kcal: 560,
    protein: 24,
    carbs: 78,
    fat: 14,
    prepTime: 20,
    cost: 2.0,
    freshnessTier: 3,
    allergenTags: [],
    highGI: false,
    image: '🌶️',
    ingredients: [
      { name: 'Haricots rouges cuits', quantity: '200 g' },
      { name: 'Maïs', quantity: '80 g' },
      { name: 'Tomates concassées', quantity: '200 g' },
      { name: 'Riz basmati', quantity: '80 g (poids sec)' },
    ],
    steps: ['Mijoter haricots, maïs et tomates 15 min avec épices.', 'Servir sur le riz basmati.'],
  },
  {
    id: 'r-midi-8',
    slot: 'midi',
    name: 'Salade César au poulet grillé',
    kcal: 540,
    protein: 44,
    carbs: 28,
    fat: 26,
    prepTime: 12,
    cost: 3.5,
    freshnessTier: 1,
    allergenTags: ['Œufs', 'Lactose', 'Poisson / Crustacés'],
    highGI: false,
    image: '🥗',
    ingredients: [
      { name: 'Blanc de poulet', quantity: '150 g' },
      { name: 'Salade romaine', quantity: '100 g' },
      { name: 'Parmesan', quantity: '20 g' },
      { name: 'Sauce César', quantity: '2 c. à s.' },
    ],
    steps: ['Griller le poulet et le trancher.', 'Mélanger salade, parmesan et sauce.', 'Ajouter le poulet.'],
  },
  {
    id: 'r-midi-9',
    slot: 'midi',
    name: 'Curry de lentilles corail & riz',
    kcal: 570,
    protein: 24,
    carbs: 82,
    fat: 12,
    prepTime: 18,
    cost: 1.7,
    freshnessTier: 3,
    allergenTags: [],
    highGI: false,
    image: '🍛',
    ingredients: [
      { name: 'Lentilles corail', quantity: '120 g' },
      { name: 'Lait de coco léger', quantity: '150 ml' },
      { name: 'Riz basmati', quantity: '80 g (poids sec)' },
      { name: 'Épices curry', quantity: '1 c. à s.' },
    ],
    steps: ['Cuire les lentilles avec le lait de coco et les épices 15 min.', 'Servir sur le riz basmati.'],
  },
  {
    id: 'r-midi-10',
    slot: 'midi',
    name: 'Sandwich bagel saumon fumé & fromage frais',
    kcal: 550,
    protein: 30,
    carbs: 48,
    fat: 24,
    prepTime: 7,
    cost: 3.9,
    freshnessTier: 1,
    allergenTags: ['Gluten', 'Poisson / Crustacés', 'Lactose'],
    highGI: false,
    image: '🥯',
    ingredients: [
      { name: 'Bagel complet', quantity: '1' },
      { name: 'Saumon fumé', quantity: '80 g' },
      { name: 'Fromage frais', quantity: '30 g' },
      { name: 'Roquette', quantity: '20 g' },
    ],
    steps: ['Tartiner le bagel de fromage frais.', 'Garnir de saumon fumé et de roquette.'],
  },
  {
    id: 'r-midi-11',
    slot: 'midi',
    name: 'Falafels maison, taboulé & sauce yaourt',
    kcal: 580,
    protein: 20,
    carbs: 74,
    fat: 18,
    prepTime: 16,
    cost: 2.3,
    freshnessTier: 2,
    allergenTags: ['Gluten', 'Lactose'],
    highGI: false,
    image: '🧆',
    ingredients: [
      { name: 'Falafels', quantity: '6' },
      { name: 'Taboulé', quantity: '150 g' },
      { name: 'Yaourt nature', quantity: '60 g' },
    ],
    steps: ['Cuire les falafels au four 12 min.', 'Servir avec le taboulé et la sauce yaourt.'],
  },

  // --- Soir ---
  {
    id: 'r-soir-1',
    slot: 'soir',
    name: 'Curry de pois chiches & riz basmati',
    kcal: 540,
    protein: 20,
    carbs: 78,
    fat: 16,
    prepTime: 20,
    cost: 1.8,
    freshnessTier: 3,
    allergenTags: [],
    highGI: false,
    image: '🍲',
    ingredients: [
      { name: 'Pois chiches cuits', quantity: '250 g' },
      { name: 'Lait de coco léger', quantity: '150 ml' },
      { name: 'Riz basmati', quantity: '80 g (poids sec)' },
      { name: 'Épices curry', quantity: '1 c. à s.' },
    ],
    steps: ['Faire revenir oignon et épices.', 'Ajouter pois chiches et lait de coco, mijoter 15 min.', 'Servir sur riz basmati.'],
  },
  {
    id: 'r-soir-2',
    slot: 'soir',
    name: 'Soupe miso, tofu & nouilles soba',
    kcal: 480,
    protein: 24,
    carbs: 55,
    fat: 14,
    prepTime: 15,
    cost: 2.4,
    freshnessTier: 2,
    allergenTags: ['Soja', 'Gluten'],
    highGI: false,
    image: '🍜',
    ingredients: [
      { name: 'Nouilles soba', quantity: '80 g' },
      { name: 'Tofu ferme', quantity: '120 g' },
      { name: 'Pâte miso', quantity: '1 c. à s.' },
      { name: 'Champignons shiitake', quantity: '80 g' },
    ],
    steps: ['Cuire les nouilles séparément.', 'Préparer le bouillon miso, ajouter tofu et champignons.', 'Ajouter les nouilles avant de servir.'],
  },
  {
    id: 'r-soir-3',
    slot: 'soir',
    name: 'Cabillaud rôti, purée de patate douce',
    kcal: 500,
    protein: 36,
    carbs: 48,
    fat: 14,
    prepTime: 22,
    cost: 4.1,
    freshnessTier: 1,
    allergenTags: ['Poisson / Crustacés'],
    highGI: false,
    image: '🐟',
    ingredients: [
      { name: 'Filet de cabillaud', quantity: '160 g' },
      { name: 'Patate douce', quantity: '250 g' },
      { name: 'Épinards frais', quantity: '100 g' },
    ],
    steps: ['Rôtir le cabillaud 15 min au four.', 'Cuire et écraser la patate douce.', 'Poêler les épinards 2 min.'],
  },
  {
    id: 'r-soir-4',
    slot: 'soir',
    name: 'Chili con carne & riz complet',
    kcal: 560,
    protein: 38,
    carbs: 55,
    fat: 18,
    prepTime: 25,
    cost: 3.3,
    freshnessTier: 1,
    allergenTags: [],
    highGI: false,
    image: '🌶️',
    ingredients: [
      { name: 'Bœuf haché 5%', quantity: '150 g' },
      { name: 'Haricots rouges', quantity: '150 g' },
      { name: 'Tomates concassées', quantity: '200 g' },
      { name: 'Riz complet', quantity: '70 g (poids sec)' },
    ],
    steps: ['Faire revenir le bœuf haché.', 'Ajouter haricots et tomates, mijoter 15 min.', 'Servir sur le riz.'],
  },
  {
    id: 'r-soir-5',
    slot: 'soir',
    name: 'Poêlée de crevettes, courgettes & vermicelles',
    kcal: 470,
    protein: 32,
    carbs: 50,
    fat: 12,
    prepTime: 14,
    cost: 4.3,
    freshnessTier: 1,
    allergenTags: ['Poisson / Crustacés'],
    highGI: false,
    image: '🍤',
    ingredients: [
      { name: 'Crevettes décortiquées', quantity: '150 g' },
      { name: 'Courgette', quantity: '2' },
      { name: 'Vermicelles de riz', quantity: '70 g' },
      { name: 'Sauce soja', quantity: '1 c. à s.' },
    ],
    steps: ['Poêler les crevettes 4 min.', 'Ajouter courgettes en julienne.', 'Mélanger aux vermicelles cuits et sauce soja.'],
  },
  {
    id: 'r-soir-6',
    slot: 'soir',
    name: 'Dahl de lentilles corail, riz vapeur',
    kcal: 520,
    protein: 22,
    carbs: 80,
    fat: 10,
    prepTime: 20,
    cost: 1.6,
    freshnessTier: 3,
    allergenTags: [],
    highGI: false,
    image: '🍛',
    ingredients: [
      { name: 'Lentilles corail', quantity: '130 g' },
      { name: 'Lait de coco léger', quantity: '100 ml' },
      { name: 'Riz basmati', quantity: '70 g (poids sec)' },
      { name: 'Épinards frais', quantity: '80 g' },
    ],
    steps: ['Cuire les lentilles 15 min avec épices et lait de coco.', 'Ajouter les épinards en fin de cuisson.', 'Servir sur riz vapeur.'],
  },
  {
    id: 'r-soir-7',
    slot: 'soir',
    name: 'Omelette aux champignons & salade verte',
    kcal: 420,
    protein: 26,
    carbs: 18,
    fat: 26,
    prepTime: 12,
    cost: 2.0,
    freshnessTier: 1,
    allergenTags: ['Œufs'],
    highGI: false,
    image: '🍳',
    ingredients: [
      { name: 'Œufs', quantity: '3' },
      { name: 'Champignons de Paris', quantity: '100 g' },
      { name: 'Salade verte', quantity: '80 g' },
    ],
    steps: ['Poêler les champignons.', 'Verser les œufs battus, cuire à couvert.', 'Servir avec la salade.'],
  },
  {
    id: 'r-soir-8',
    slot: 'soir',
    name: 'Pâtes au pesto, poulet & tomates séchées',
    kcal: 610,
    protein: 40,
    carbs: 62,
    fat: 20,
    prepTime: 16,
    cost: 3.2,
    freshnessTier: 1,
    allergenTags: ['Gluten', 'Fruits à coque', 'Lactose'],
    highGI: true,
    image: '🍝',
    ingredients: [
      { name: 'Pâtes complètes', quantity: '90 g (poids sec)' },
      { name: 'Blanc de poulet', quantity: '130 g' },
      { name: 'Pesto', quantity: '2 c. à s.' },
      { name: 'Tomates séchées', quantity: '30 g' },
    ],
    steps: ['Cuire les pâtes.', 'Griller le poulet en lamelles.', 'Mélanger le tout avec le pesto.'],
  },
  {
    id: 'r-soir-9',
    slot: 'soir',
    name: 'Tofu laqué, brocolis & riz complet',
    kcal: 500,
    protein: 26,
    carbs: 58,
    fat: 16,
    prepTime: 18,
    cost: 2.5,
    freshnessTier: 2,
    allergenTags: ['Soja'],
    highGI: false,
    image: '🥢',
    ingredients: [
      { name: 'Tofu ferme', quantity: '160 g' },
      { name: 'Brocolis', quantity: '200 g' },
      { name: 'Riz complet', quantity: '70 g (poids sec)' },
      { name: 'Sauce teriyaki', quantity: '2 c. à s.' },
    ],
    steps: ['Saisir le tofu mariné.', 'Cuire les brocolis vapeur.', 'Servir sur riz complet, napper de sauce.'],
  },
  {
    id: 'r-soir-10',
    slot: 'soir',
    name: 'Papillote de saumon, riz & légumes croquants',
    kcal: 560,
    protein: 36,
    carbs: 50,
    fat: 20,
    prepTime: 24,
    cost: 4.4,
    freshnessTier: 1,
    allergenTags: ['Poisson / Crustacés'],
    highGI: false,
    image: '🐟',
    ingredients: [
      { name: 'Pavé de saumon', quantity: '150 g' },
      { name: 'Riz complet', quantity: '70 g (poids sec)' },
      { name: 'Carottes', quantity: '100 g' },
      { name: 'Citron', quantity: '1/2' },
    ],
    steps: ['Cuire le saumon et les carottes en papillote 20 min.', 'Servir avec le riz complet.'],
  },
]
